### ISSUE TITLE
Artitalk安全

### ISSUE THREAD

**Issue by Linhk1606** [ArtitalkJS/Artitalk#15]
请按照此模板编写issue

**描述你想实现或修改的功能**

感觉Artitalk有些机制不太安全

1. 图片上传，似乎调用了GitHub的API存到一个叫@Artitalk的用户的仓库里，总感觉有点不太安全，以后能否改成存到用户自己建的GitHub仓库里
1. 关于点赞功能 #12 

**其他内容**

**Comment by Drew233** [comment]
图片这个确实很多人提过，可以考虑下次提供一个接口，供大家自行选择

点赞功能，实在不行的话，准备删除23333

**Comment by Linhk1606** [comment]
啊呜呜呜呜呜不要删啊

**Comment by Drew233** [comment]
点赞我也有点不舍得删（写了好久的。
那个自定义存储的接口写好了，马上更新文档
但是之前为什么不加自定义存储呢，就是因为这样的话相当于你的token就暴漏在外面了，所以才会申请了一个信号专门来存储。
不过既然都有需求，还是加上了😝

**Comment by Drew233** [comment]
*新号

**Comment by Linhk1606** [comment]
> *新号

可以直接edit的😅

**Comment by Drew233** [comment]
嗯嗯

**Comment by Drew233** [comment]
v2.3.4已解决第一个问题

关于点赞的事，慢慢来吧，还没想到什么好办法

**Comment by zygds** [comment]
> v2.3.4已解决第一个问题
> 
> 关于点赞的事，慢慢来吧，还没想到什么好办法
我有一个好渠道https://widgetpack.com/可以试一下这个类似于
![image](https://user-images.githubusercontent.com/50038957/88569146-96024d00-d06c-11ea-94bc-b0918130a4ad.png)
你可以试试
顺便问一下，图片存储能不能改成gitee
类似https://gitee.com/zygds/Typora-image-upload/raw/master/image/image-20200717173257144.png
但是也需要tocken ，，难啊！
能不能用一个小号来作为存储库服务
难啊

**Comment by Drew233** [comment]
token泄露的问题已经解决了
不准备用gitee，相比github来说没有很明显的优点

点赞那个我去看看
