### ISSUE TITLE
奇怪的bug 点击登陆没反应

### ISSUE THREAD

**Issue by zhu-jl18** [ArtitalkJS/Artitalk#19]
啊这 按照教程配置完之后 一切正常
也出现了
--
如果你看到这条说说，恭喜你已经配置成功并且可以正常使用了。当你发布一个说说之后，我将会自动消失。快去探索Artitalk吧
欢迎加入Artitalk的QQ交流群：1104585229
觉得本项目不错的话可以推荐给你的好友或者去GitHub点一个star，感谢支持
--
但是登录用户时点击登录就是没反应，这是什么神奇的bug吗

**Comment by zhu-jl18** [comment]
控制台报错信息

artitalk.js:7 Uncaught Error: Not initialized
    at p (artitalk.js:7)
    at _request (artitalk.js:7)
    at r.logIn (artitalk.js:7)
    at Function.logIn (artitalk.js:7)
    at Login (artitalk.js:7)
    at HTMLInputElement.onclick ((index):443)

**Comment by Drew233** [comment]
有你的链接吗？

**Comment by zhu-jl18** [comment]
有 https://zhu-jl18.github.io

**Comment by Drew233** [comment]
![image](https://user-images.githubusercontent.com/47592224/87381511-7cbac480-c5c7-11ea-861d-2e214671162f.png)
你可以试试把这里面后面的那个链接改成
https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
试试
