### ISSUE TITLE
自定时间戳

### ISSUE THREAD

**Issue by Guanchishan** [ArtitalkJS/Artitalk#24]
请按照此模板编写issue

**描述你想实现或修改的功能**
开发者辛苦了！有无打算添加自定时间戳的功能呢？
目前artitalk应该就是直接调用创建时间：
![image](https://user-images.githubusercontent.com/30859354/88906208-bd823100-d289-11ea-853f-d191c84cdfad.png)
Valine的话调用的是可以编辑的时间戳：
![image](https://user-images.githubusercontent.com/30859354/88906295-de4a8680-d289-11ea-9ef7-8618a1fce39d.png)
这样子或许在导入其他社交媒体发言的时候，就能更好地体现原时间戳了。<s>就可以放心退博了</s>

**其他内容**
如果artitalk想在时间戳上体现公信力，可以设计个标记显示这个时间戳有被改过hhh不过时间公证很明显是第三方来做的事情。

**Comment by Drew233** [comment]
😂这个没有很大必要吧，毕竟我们使用的就是发表时间

引用的话直接在内容里面标注一下就好了

**Comment by Guanchishan** [comment]
也有道理hhh多谢！
