### ISSUE TITLE
点赞按钮使用 float: right 会导致一些潜在的问题

### ISSUE THREAD

**Issue by YexuanXiao** [ArtitalkJS/Artitalk#26]
**描述**
点赞按钮使用 float:right 会导致特定情况下按钮溢出到说说内容 ( li ) 外面。

**出现bug的页面**
页面链接：https://mysteriouspreserve.com/artitalk

**重现**
当且仅当“平台+时间”占用一整行（不换行）并且该行没有足够的位置容纳点赞按钮时出现此情况，常见于移动端。

**截图**
![截图](https://s1.ax1x.com/2020/08/06/agbJeI.png)

**Comment by Drew233** [comment]
嗯嗯，之前也有人反映过这个问题，下个版本会尽力解决👌

**Comment by YexuanXiao** [comment]
> 嗯嗯，之前也有人反映过这个问题，下个版本会尽力解决👌

用 float 就会导致元素潜在的脱离文档，感觉原生 css 没有什么好方法。
对 artitalk_star_svg 的父级元素应用下列样式可以解决这个问题。

    right: 0;
    position: absolute;
    margin-right: 1em;

**Comment by Drew233** [comment]
哇，非常感谢🙏
我的css基础不是很好，真的非常感谢

**Comment by YexuanXiao** [comment]
> 哇，非常感谢🙏
> 我的css基础不是很好，真的非常感谢

我发现这个也有问题，会导致元素重叠。。。。

**Comment by Drew233** [comment]
啊这，没事，我多琢磨琢磨，肯定可以解决的

**Comment by jerryc127** [comment]
可以考慮用 display: flex
![image](https://user-images.githubusercontent.com/16351105/90053123-a2dd9c80-dd0c-11ea-8492-56dae568951f.png)
