### ISSUE TITLE
显示加载成功，无法使用

### ISSUE THREAD

**Issue by cuihuan** [ArtitalkJS/Artitalk#48]
**显示**
如果你看到这条说说，恭喜你已经配置成功并且可以正常使用了。当你发布一个说说之后，我将会自动消失。快去探索Artitalk吧
欢迎加入Artitalk的QQ交流群：1104585229
觉得本项目不错的话可以推荐给你的好友或者去GitHub点一个star，感谢支持

但是总是登录失败，什么原因：url=>http://cuihuan.net/shuoshuo/
--------------------------------------
console 报错：
init.js?ddd7:165 Uncaught TypeError: Cannot redefine property: applicationId
    at Function.defineProperty (<anonymous>)
    at init.js?ddd7:165
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (init.js?ddd7:174)
    at e (bootstrap bacf8240e97c4b30b3d3?b629:19)
    at Object.<anonymous> (index.js?9552:19)
    at e (bootstrap bacf8240e97c4b30b3d3?b629:19)
    at bootstrap bacf8240e97c4b30b3d3?b629:65
    at bootstrap bacf8240e97c4b30b3d3?b629:65
    at universalModuleDefinition?5ca6:9

**Comment by Drew233** [comment]
大概率是因为valine，因为现在暂时不支持和valine在同一个界面使用（受到leancloud的限制）
next主题应该是支持单页面禁用评论的，你可以试一下

**Comment by cuihuan** [comment]
去掉了valine在这个页面的评论，还是不行

**Comment by cuihuan** [comment]
主要是valine冲突，删除掉冲突代码就可以
1、当前页面关闭comments
`comments: false
`
2、valine删除   <script src="//cdn1.lncld.net/static/js/3.0.4/av-min.js"></script>
