### ISSUE TITLE
图片上传

### ISSUE THREAD

**Issue by WangHeng93** [ArtitalkJS/Artitalk#51]
**图片、音频等上传**
之前版本还有的图片上传等功能好像删除了，不知道是出于什么考虑。请问以后会考虑添加吗？

**已上传的资料**
之前版本发布的说说里包含的图片等资源不会删除吧，请问需要个人自行迁移吗？

谢谢！

**Comment by Drew233** [comment]
对的删除了，因为不是很稳定，以后有好的解决方式会考虑的
之前资源不会删除

**Comment by ChenYFan** [comment]
1.主要是上传原因。默认上传至github，姑且不说github加速下载，上传的连通性就是个大问题
2.还有安全原因，github上传用的是iartitalk官方的githubtoken，很有可能存在滥用行为，所以不得不中止

**Comment by WangHeng93** [comment]
好的哈，希望以后能有更好的方式。
