### ISSUE TITLE
点击“登录”没有反应

### ISSUE THREAD

**Issue by Reyna-Jin** [ArtitalkJS/Artitalk#60]
我是用hexo创建个人博客，其中“说说”界面用到artitalk，界面如下：
![image](https://user-images.githubusercontent.com/34954076/99561032-80d97180-2a01-11eb-8396-c7fd816b6d8f.png)
但点击右下角输入账号密码后没有反应，请问是怎么回事？
![image](https://user-images.githubusercontent.com/34954076/99561139-9f3f6d00-2a01-11eb-9eba-9feb7bf1b9a2.png)
谢谢各位大佬！

**Comment by Drew233** [comment]
提供个链接吧
可能导致这个问题的原因最大可能就是页面中使用了多个leancloud应用导致冲突以至于登录失败
也有可能是密码错误

**Comment by Reyna-Jin** [comment]
链接：https://reyna-jin.github.io/artitalk/
我又试了试，还是不可，就是点击登录没有反应，账号密码是Leancloud登录的账号密码吧

**Comment by Drew233** [comment]
账号密码是你自己在leancloud应用中添加的用户的用户密码
不是leancloud的

**Comment by Reyna-Jin** [comment]
呀呀呀，我成功啦，原来是密码输错啦，谢谢您！！！！

**Comment by Drew233** [comment]
解决了就行😁
