### ISSUE TITLE
自定义图床

### ISSUE THREAD

**Issue by YiHui-Liu** [ArtitalkJS/Artitalk#67]
**描述你想实现或修改的功能**
现在默认使用去不图床，可以增加一个配置项，使用自定义图床吗

**Comment by Drew233** [comment]
这个不是很好实现而且没有必要
如果想用其它图床可以上传完在写到说说里的

**Comment by YiHui-Liu** [comment]
我现在就是用其它图床可以上传完再写进去的，这样就是有点麻烦（捂脸
后面再研究一下，谢谢啦

**Comment by Drew233** [comment]
嗯嗯，因为每个图床给的接口不一定一样，给自定义太麻烦了 
但是如果你想用的图床是提供了接口的那种大一点的图床 可以考虑新增，但不一定每个图床都支持跨域 当时本来想用smms，就是跨域不行所以放弃了
