### ISSUE TITLE
添加完整的媒体文件播放支持

### ISSUE THREAD

**Issue by MCSeekeri** [ArtitalkJS/Artitalk#70]
**加入对各种媒体文件的播放支持**
其实也不是各种（支持mp4让我很惊喜
我之前用MD语法引用了不少mp3文件作为推歌,但这次更新似乎删掉了对mp3文件的播放支持（
看起来mp3文件还是会正常加载的,所以只需调用浏览器默认的播放就可以了（

**其他内容**
无（

**Comment by Drew233** [comment]
mp3和mp4等媒体文件的播放与artitalk是无关的呀，这是浏览器支持的。之前的artitalk也只是提供了一个上传后自动提供html格式的功能。
不能播放的话建议尝试使用一下网上教程中的其他的html格式。

**Comment by MCSeekeri** [comment]
这就有点奇怪了...
之前的版本在火狐上面是可以正常播放mp3的...升级Artitalk之后就不显示播放器了,但F12是可以看到加载了mp3文件的...

**Comment by Drew233** [comment]
可能是由于之前版本我是写好了mp3文件的html？
我也不知道是什么原因导致的，还需要帮忙解决的话可以留个链接🍺

**Comment by MCSeekeri** [comment]
吼（
https://mcseekeri.top/talk/
在这里我引用了一个mp3文件,但是就是不显示播放器（捂脸

**Comment by Drew233** [comment]
是我去晚了嘛？没看到有mp3鸭

**Comment by MCSeekeri** [comment]
啊..大概是我没说明白罢（
唯一一条说说前面有个空格,那里理论上该显示播放器的（
我用的`![](https://啥啥啥/文件名.mp3`这种方式引用的,旧版本都能正常显示,自从3.x之后似乎就不行了（

**Comment by Drew233** [comment]
嗯，问题就是你这样写引入mp3在内置的js进行转换的时候无法转换出来可以显示的播放器形式。建议直接使用html格式哟~

**Comment by MCSeekeri** [comment]
大概明白了...就是用Aplayer之类?

**Comment by Drew233** [comment]
对，但是html似乎原生就有支持mp3的语法。之前Artitalk用的就是

**Comment by MCSeekeri** [comment]
问题解决力（
