### ISSUE TITLE
一直处于加载中（下雨界面）

### ISSUE THREAD

**Issue by junono97** [ArtitalkJS/Artitalk#80]
按照要求填入以下index.md
```
---
title: shuoshuo
date: 2021-06-29 21:41:13
comments: false
---
<!-- 引用 artitalk -->
<script src="https://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
<script type="text/javascript" src="https://unpkg.com/artitalk"></script>

<!-- 存放说说的容器 -->
<div id="artitalk_main"></div>
<script>
new Artitalk({
    appId: 'xxx', // Your LeanCloud appId
    appKey: 'xxx' // Your LeanCloud appKey
})
</script>
```
可是还是一直处于加载中（下雨界面），下面是审查元素，这是什么问题呢？
![image](https://user-images.githubusercontent.com/57182325/123812745-eb9f4380-d926-11eb-8eea-4ce5ba662d16.png)

**Comment by zhaoze-jpg** [comment]
![5KW8CUUGVF}EEZZ@M9CV1_K](https://user-images.githubusercontent.com/76829546/127328286-29695549-23b3-4f3e-8be8-785b0ccb59b4.png)
我也老下雨

**Comment by zhaoze-jpg** [comment]
我的 http://ze520.cn/census/

**Comment by Drew233** [comment]
> 我的 http://ze520.cn/census/

你这个是shuoshuo的class权限出问题，报错里面写的是find权限，自己在检查一下

**Comment by zhaoze-jpg** [comment]
> > 我的http://ze520.cn/census/
> 
> 你这个是说硕的类权限出问题，报错里面写的是找到权限，自己在检查一下

谢谢已经解决了
