### ISSUE TITLE
可以加个返回按钮

### ISSUE THREAD

**Issue by SaraKale** [ArtitalkJS/Artitalk#92]
这个项目真的很不错！目前有个小小的功能建议，就是能否加上“返回”按钮呢？就是给一个小伙伴的说说评论了之后还以为还在说说首页，但是按浏览器后退键有时候会退回到博客首页，有点不太方便的样子~可能是我这边的BUG？/(ㄒoㄒ)/~~

另外顺便求夜间模式适配，我自己写了样式，但是有一个小地方没法改颜色，看起来是固定的样子改不了了
![](https://test.7bu.top/i/2022/05/09/6279226aa39b2.jpg)
![](https://test.7bu.top/i/2022/05/09/62792374943ee.jpg)

**Comment by Drew233** [comment]
因为评论了并没有跳转页面，所以浏览器后退键才返回了，这里设计的是在评论页面再点一个评论的图标就返回，你可以把这当成是一个 “巧妙” 的设计（我不知道返回放在哪好看了

夜间模式那个以后可以考虑一下~

**Comment by SaraKale** [comment]
> 因为评论了并没有跳转页面，所以浏览器后退键才返回了，这里设计的是在评论页面再点一个评论的图标就返回，你可以把这当成是一个 “巧妙” 的设计（我不知道返回放在哪好看了
> 
> 夜间模式那个以后可以考虑一下~

原来如此！我还找了半天按钮哩！哈哈这个小问题也没事！以后再完善~！按钮的位置可以放左上角也行～
感谢你开发了如此棒的项目！送个小鲜花聊表谢意～:hibiscus::hibiscus:
