### ISSUE TITLE
表情文件cdn修改

### ISSUE THREAD

**Issue by BowenYoung** [ArtitalkJS/Artitalk#94]
请按照此模板编写issue

**描述你想实现或修改的功能**
cdn.jsd挂了，但我看源码中表情貌似仍用的cdn.jsd，不知道是否考虑过换成其他cdn或改成fastly.jsd之类的呢

**其他内容**
无

**Comment by BowenYoung** [comment]
辛苦了！

**Comment by Drew233** [comment]
v3.3.1修改过了，感谢支持~🌹
